{{ config(materialized='table') }}

WITH CUSTOMERORDER AS (
    SELECT C.CUSTOMERID, CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME, COUNT(O.ORDERID) AS ORDERCOUNT
    FROM {{ source('landing', 'customers') }} C
    JOIN {{ source('landing', 'orders') }} O ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY C.CUSTOMERID, CUSTOMERNAME
    ORDER BY ORDERCOUNT DESC
)

SELECT CUSTOMERID, CUSTOMERNAME, ORDERCOUNT
FROM CUSTOMERORDER
